### ISSUE TITLE
Improve Decimal handling

### ISSUE THREAD

**Issue by ivosturm** [mendix/AuditTrailModule#15]
Currently the module doesn't handle Decimals correctly. There are two problems, one really a bug and the other would be a nice improvement:

**BUG:** In the database the Decimal is always stored with 8 decimals. If on the page the Decimal attribute's UI is set to for instance 2 decimals, every time this attribute is committed, the module interprets this as a change, because it checks the value with 2 decimals with the one with 8 decimals, which will never agree.
**Upgrade:** The module always stores 8 decimals. When there are trailing zeros it would be nice to being able to not show those.

See also forum post: https://forum.mendixcloud.com/link/questions/98479

**Comment by nimatrueway** [comment]
> BUG: In the database the Decimal is always stored with 8 decimals. If on the page the Decimal attribute's UI is set to for instance 2 decimals, every time this attribute is committed, the module interprets this as a change, because it checks the value with 2 decimals with the one with 8 decimals, which will never agree.

I may not have understood the issue here. I kept the decimal attribute unchanged in my case, and there was no report of it being changed. Would you give me a clear-cut reproduction scenario?

![peek](https://user-images.githubusercontent.com/2261274/83808853-c4d7f480-a6b5-11ea-8499-d95447256eff.gif)

>  Upgrade: The module always stores 8 decimals. When there are trailing zeros it would be nice to being able to not show those.

The `old value` indeed shows the full representation with trailing zero, it's a good suggestion to make it display like `new value` with trailing zeros trimmed. :+1:

**Comment by sti-zuehlke** [comment]
We encountered the same issue and patched an internal method " "getMemberValueString(member, fromCache, context)" of Class "audittrail.log.CreateLogObject"

We added:

if (value instanceof BigDecimal)
                return ((BigDecimal) value).stripTrailingZeros().toPlainString();
                
Maybe you could integrate this?

**Comment by dahfjkg** [comment]
We addressed this problem in the latest release of the module: 8.1.2 for Mendix 8 and 9.0.2 for Mendix 9
